### ISSUE TITLE
Accessing the communication interface

### ISSUE THREAD

**Issue by abedStatic** [WAGO/cc100-howtos#1]
Hello,

I'm trying to connect my 3 phase [WAGO Power Module](https://www.wago.com/global/current-transformers-and-voltage-taps/3-phase-power-measurement-module/p/2857-570_024-001) to measure and view 3 phase voltages, currents, etc... 
Is it possible to access these parameters from the power module using the WAGO CC100? It appears that the CC100 has an onboard RS-485 input, and the Power module can transmit its data using Modbus RTU through the same kind if connection.

Thanks!

**Comment by Helmut-Saal** [comment]
Hello, this is a "normal" Support question, please contact Wago Support or your local sales. 
No issue => closed.
